{% set python_min = "3.10" %}
{% set name = "hierarchicalsoftmax" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hierarchicalsoftmax-{{ version }}.tar.gz
  sha256: 0f072d83193311b48ad36492c0e070a6e9d6729ef3e85e2a5e67a434ae1f0486

build:
  entry_points:
    - treedict = hierarchicalsoftmax.treedict:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - anytree >=2.8.0
    - pytorch >=1.10.2
    - rich >=10.16.1
    - scikit-learn >=1.1.1
    - torchmetrics >=1.4.0.post0
    - python-graphviz >=0.20.3
    - plotly >=5.0.0
    - attrs >=25.3.0
    - typer >=0.15.4

test:
  imports:
    - hierarchicalsoftmax
  commands:
    - pip check
    - treedict --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://rbturnbull.github.io/hierarchicalsoftmax
  doc_url: https://rbturnbull.github.io/hierarchicalsoftmax
  dev_url: https://github.com/rbturnbull/hierarchicalsoftmax
  summary: A Hierarchical Softmax Framework for PyTorch.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apcamargo
